### ISSUE TITLE
Jestercap doesn't want to open

### ISSUE THREAD

**Issue by Akira298** [crashb/jestercap#5]
I've downloaded the last version of jestercap for spelunky 2 v1.18.0 but it doesn't want to open, even the one right before didn't wanted to open before the update of spelunky 2. The only one that wanted to work was JesterCap_1.17.0f_02 and that's it. .NET is at the lastest version aswell.

**Comment by crashb** [comment]
Hey, thanks for letting me know. It sounds like this is a problem with JesterCap and not a problem with Spelunky. You're not the only person who has had this issue (@Adrad1234) so I am interested in resolving it as best as I can.

It sounds like the application is crashing when it tries to load the configuration file. Please confirm that the directory structure looks as follows:
![image](https://user-images.githubusercontent.com/10488673/100295871-04d2b280-2f48-11eb-96b8-c0f33c445f2a.png)

The JesterCap.exe.config file should look like this by default:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.8" />
    </startup>
	<appSettings>
		<add key="warningTimes" value="5, 2.5, 1"/>
	</appSettings>
</configuration>
```

If something is changed in this file that causes the XML to be invalid, that might cause the issue you're seeing. Let me know if you changed anything in here.

I'll also be uploading another release which improves the handling of this configuration file which warns you and automatically loads the default if it does not find the "warningTimes" configuration key.

**Comment by Akira298** [comment]
I haven't changed anything on the file and everything looks like you showed here

**Comment by crashb** [comment]
I've released a new build ([1.18.0_02](https://github.com/crashb/jestercap/releases/tag/1.18.0_02)). Let me know if it works better for you.

Also, did you extract the files to a local folder before running the .exe? If you were to just run the .exe from the archive, that would cause this issue. Either way, the extraction step is missing from the README so I've gone ahead and added it.

**Comment by Akira298** [comment]
Jestercap opens with the lastest version however i'm not able to attach it with spelunky 2. When i try it just closes it. And to answer your question yes i've extracted the files to a local folder before running it

**Comment by crashb** [comment]
Thanks for all the good info. I've got one last thing to try which I've included in another, newer release ([1.18.0_03](https://github.com/crashb/jestercap/releases/tag/1.18.0_03)). Let me know whether this release works for you.

**Comment by Akira298** [comment]
Still not working, same as i said right before, it's opening but unable to attach the process

**Comment by Akira298** [comment]
https://clips.twitch.tv/HotAnnoyingElephantNomNom here's a little clip about what's happening in case that helps more

**Comment by crashb** [comment]
That's really strange. I was hoping one of those releases would fix it. Thanks for the clip and all the info you've provided so far.

Clearly something is different on your machine that is causing it to not work, but I'm not sure what that might be. You could try running the exe as admin or any other number of typical Windows troubleshooting steps.

Fortunately, this is an open-source project, so you can download the code and try to compile on your end. It will require a bit of setup but we'll be able to more effectively diagnose your issue. Here's a step-by-step guide on how to do that:

- Install [VS Community](https://visualstudio.microsoft.com/vs/community/) with the ".NET desktop development" workload checked
![image](https://user-images.githubusercontent.com/10488673/100308635-1925a800-2f66-11eb-8c23-ed4a6aea3b3d.png)
- Download the JesterCap source code (either as a .zip file from the main GitHub page, or you can use Git)
![image](https://user-images.githubusercontent.com/10488673/100308765-6570e800-2f66-11eb-8741-1bb0ae44f5e1.png)
- Open `JesterCap.sln` in Visual Studio
- Build in Debug for x64 platform:
![image](https://user-images.githubusercontent.com/10488673/100308582-f7c4bc00-2f65-11eb-938c-22700aa41bf9.png)
- JesterCap might fail to build, at which point you could troubleshoot the issue further with the error message that gets provided
- Alternatively, JesterCap might successfully build, but when it crashes in Debug mode you should be able to get a more verbose error message that can help us narrow down the cause.

Let me know if you have any questions on any of these steps.

**Comment by Akira298** [comment]
decided to take multiple screen for you, so jestercap opens correctly but yeah there's definitely a problem during attaching the process to it here's what i got (hope french won't annoy you to identify)
![QjoRRLu2Py](https://user-images.githubusercontent.com/75041698/100362687-0958a300-2ffc-11eb-9703-53d1e1d58713.png)
![1lJKFkaJTl](https://user-images.githubusercontent.com/75041698/100362693-0a89d000-2ffc-11eb-9c29-9b836751e203.png)
![L4Sdp5Uvdl](https://user-images.githubusercontent.com/75041698/100362698-0bbafd00-2ffc-11eb-9c30-97ed45afa8ce.png)

**Comment by crashb** [comment]
Thanks for jumping through all those hoops to provide details.

It turns out that Windows regional settings affect decimal parsing, which I did not know. Decimals are written "2,5" instead of "2.5" in some places. I'll be uploading another build to fix this but for now you should be good if you remove the decimal from the config file altogether; make it "5, 2, 1" or something.

**Comment by Akira298** [comment]
yeah, removing the decimal fixed the problem. i just tested it and now it works perfectly fine. Thank you a lot for your time.

**Comment by crashb** [comment]
I've uploaded another release ([1.18.0_04](https://github.com/crashb/jestercap/releases/tag/1.18.0_04)) that fixes this. You should be able to use timings with decimals now.

I'll go ahead and close this issue now but let me know if you continue to encounter problems.
